apiVersion: argoproj.io/v1alpha1
kind: Notification
metadata:
  name: chap-notify
  namespace: argo
spec:
  monitorResource:
    Group: 
    Resource: pods
    Version: v1
  Namespace: argo
  notifiers:
  - name: slack
    slack:
      channel: general
      hookUrlSecret:
        key: hookURL
        name: my-slack-secret
  rules:
  - allConditions:
    - 
      # Json Path for element need to validate
      jsonPath: status/phase
      # Operator
      operator: eq
      # value
      value: Running
    events:
        -
          message: "Pod = {{.metadata.name}} Changed status to {{.status.phase}} - restarts: {{.status.containerStatuses.restartCount}}"
          notificationLevel: info
          notifierNames:
            - slack
    initialDelaySec: 1
    name: rule2
    throttleMinutes: 1
