---
apiVersion: argoproj.io/v1alpha1
kind: Notification
metadata:
  name: notification-2
spec:
  # Define resource need to be monitor.
  monitorResource:
    Group: argoproj.io
    Resource: workflows
    Version: v1alpha1
  #
  Namespace: default
  # Define the notifiers channel. Slack and email is supporting currently
  rules:
    -
      name: rule1
      anyConditions:
        -
          jsonPath: status/phase
          operator: eq
          value: Failed
        -
          jsonPath: status/phase
          operator: eq
          value: Error
      events:
        -
          message: "Workflow ={{.metadata.name}} Failed."
          emailSubject: "[ALERT] Argo Notification Condition Triggered {{.metadata.name}}"
          notificationLevel: "warning"
          notifierNames:
            - "slack"
            - "email"
  notifiers:
    -
      name: slack
      slack:
        hookUrlSecret:
          name: my-slack-secret
          key: hookURL
        channel: testargonotification
    -
      name: email
      email:
        smtphost: smtp.gmail.com
        smtpport: 465
        # Save the smtp service credential in secret in monitoring namespace
        usernameSecret:
          name: my-email-secret
          key: username
        passwordSecret:
          name: my-email-secret
          key: password
        FromEmailId: sarabala1979@gmail.com
        SenderList:
          - saravanan_balasubramanian@intuit.com
        initialDelaySec: 60
        throttleMinutes: 5